num_workers: 4
pin_memory: True
non_blocking: True
prefetch: False
amp: False
device: cuda:0
client_optimizer: sgd
dataset: cifar100
dataset_path: ../data
frequency_save: 0
batch_size: 64
lr: 0.001
lr_scheduler: CosineAnnealingLR
model: swin_t
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
epochs: 10
split_ratio: 0.02